# name: Deploy To Environment
# description: Deploys to a specified environment

# inputs:
#   validateOnly:
#     description: 'Run the deployment as validation only'
#     type: boolean
#   environmentName:
#     description: 'The name of the environment you are deploying to'
#     type: string
#     required: true
#   sfdx_auth_url:
#     description: 'The auth url tied to your deployment environment'
#     required: true

# runs:
#   using: 'composite'
#   steps:
#     - name: Install sfdx
#       shell: bash
#       run: |
#         npm install --global sfdx-cli
#         sfdx --version
#     - name: Login to ${{ inputs.environmentName }}
#       shell: bash
#       run: |
#         sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.sfdx_auth_url }}")
#     - name: Generate package.xml
#       shell: bash
#       run: |
#         sfdx project generate manifest --source-dir force-app --output-dir manifest
#     - name: Deploy to ${{ inputs.environmentName }}
#       shell: bash
#       run: |
#         deployFlags=(
#             --manifest manifest/package.xml
#             --wait 30
#             --test-level RunLocalTests
#             --verbose
#           )
#         if [ "${{ inputs.validateOnly }}" = "true" ]; then
#           deployFlags+=( --dry-run )
#         fi
#         sfdx project deploy start "${deployFlags[@]}"
name: Deploy Using JWT
description: Authenticates with JWT and deploys specific package

inputs:
  instanceUrl:
    description: 'Salesforce instance URL (e.g., https://login.salesforce.com)'
    required: true
  clientId:
    description: 'Consumer Key of the connected app'
    required: true
  username:
    description: 'Salesforce username (integration user)'
    required: true
  keyFilePath:
    description: 'Path to JWT private key file'
    required: true
  alias:
    description: 'Alias for the authenticated org'
    required: true
  manifestPath:
    description: 'Path to the package.xml manifest file'
    required: true
  testsToRunFile:
    description: 'Path to the text file listing test classes to run'
    required: true
  validateOnly:
    description: 'Run the deployment as validation only'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Salesforce CLI
    run: |
      wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
      sudo mkdir ~/sfdx-cli
      sudo tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx-cli --strip-components 1
      export PATH=$PATH:~/sfdx-cli/bin
      echo "~/sfdx-cli/bin" >> $GITHUB_PATH
      sudo chmod -R 777 ~/sfdx-cli
      sfdx --version

    - name: Authenticate using JWT (sf CLI)
      shell: bash
      run: |
        sf org login jwt \
          --client-id "${{ inputs.clientId }}" \
          --jwt-key-file "${{ inputs.keyFilePath }}" \
          --username "${{ inputs.username }}" \
          --alias "${{ inputs.alias }}" \
          --instance-url "${{ inputs.instanceUrl }}"

    - name: Deploy package
      shell: bash
      run: |
        testClasses=$(paste -sd, < "${{ inputs.testsToRunFile }}")
        deployFlags=(
          --manifest "${{ inputs.manifestPath }}"
          --target-org "${{ inputs.alias }}"
          --test-level RunSpecifiedTests
          --runtests "$testClasses"
          --wait 30
          --verbose
          --json
        )
        if [ "${{ inputs.validateOnly }}" = "true" ]; then
          deployFlags+=( --dry-run )
        fi
        sf project deploy start "${deployFlags[@]}"