name: 'Deploy to Salesforce'
description: 'Reusable action to deploy metadata to Salesforce using JWT'
inputs:
  instanceUrl:
    required: true
    description: 'Salesforce login URL (e.g., https://login.salesforce.com)'
  clientId:
    required: true
    description: 'Connected App client ID'
  username:
    required: true
    description: 'Salesforce username'
  keyFilePath:
    required: true
    description: 'Path to JWT server key file'
  alias:
    required: true
    description: 'SFDX alias to set for the org'
  manifestPath:
    required: true
    description: 'Path to package.xml file'
  testsToRunFile:
    required: true
    description: 'Path to file listing Apex test classes'
  validateOnly:
    required: true
    description: 'Whether to validate the deployment only (true/false)'

runs:
  using: "composite"
  steps:
    - name: Authenticate via JWT
      run: |
        sfdx auth:jwt:grant \
          --clientid "${{ inputs.clientId }}" \
          --jwtkeyfile "${{ inputs.keyFilePath }}" \
          --username "${{ inputs.username }}" \
          --instanceurl "${{ inputs.instanceUrl }}" \
          --setalias "${{ inputs.alias }}"

    - name: Display Org Info
      run: sfdx force:org:display --targetusername "${{ inputs.alias }}" --verbose

    - name: Read Apex tests to run
      id: read-tests
      run: |
        TESTS=$(cat "${{ inputs.testsToRunFile }}" | paste -sd, -)
        echo "testclasses=$TESTS" >> $GITHUB_OUTPUT

    - name: Deploy Metadata
      run: |
        echo "Running deployment with validateOnly=${{ inputs.validateOnly }}"
        sfdx force:source:deploy \
          --manifest "${{ inputs.manifestPath }}" \
          --targetusername "${{ inputs.alias }}" \
          --testlevel RunSpecifiedTests \
          --runtests "${{ steps.read-tests.outputs.testclasses }}" \
          --wait 60 \
          ${{ inputs.validateOnly == 'true' && '--checkonly' || '' }}
