name: Deploy Using JWT
description: Authenticates with JWT and deploys specific package

inputs:
  instanceUrl:
    description: 'Salesforce instance URL (e.g., https://login.salesforce.com)'
    required: true
  clientId:
    description: 'Consumer Key of the connected app'
    required: true
  username:
    description: 'Salesforce username (integration user)'
    required: true
  keyFilePath:
    description: 'Path to JWT private key file'
    required: true
  alias:
    description: 'Alias for the authenticated org'
    required: true
  manifestPath:
    description: 'Path to the package.xml manifest file'
    required: true
  testsToRunFile:
    description: 'Path to the text file listing test classes to run'
    required: true
  validateOnly:
    description: 'Run the deployment as validation only'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Authenticate using JWT (sf CLI)
      shell: bash
      run: |
        sf org login jwt \
          --client-id "${{ inputs.clientId }}" \
          --jwt-key-file "${{ inputs.keyFilePath }}" \
          --username "${{ inputs.username }}" \
          --alias "${{ inputs.alias }}" \
          --instance-url "${{ inputs.instanceUrl }}"

    - name: Deploy package
      shell: bash
      run: |
        testClasses=$(paste -sd, < "${{ inputs.testsToRunFile }}")
        deployFlags=(
          --manifest "${{ inputs.manifestPath }}"
          --target-org "${{ inputs.alias }}"
          --test-level RunLocalTests
          --wait 30
          --verbose
          --json
        )
        if [ "${{ inputs.validateOnly }}" = "true" ]; then
          deployFlags+=( --dry-run )
        fi
        sf project deploy start "${deployFlags[@]}"
