/*
----------------------------------------------------------------------
-- - Name              :  BackInStockWrapper
-- - Author            :  Abdelaaziz Idaoumahmoud
-- - Description       :  Wrapper for Back In Stock batch and Helper
-- Maintenance History :    
--
-- Date                 Name                        Version          Remarks
-- -----------          -----------                 --------         ----------------------
-- 30-05-2022           Abdelaaziz Idaoumahmoud    	1.0              Initial version
---------------------------------------------------------------------------------------
*/

public with sharing class BackInStockWrapper {
    
    public String sku;
	public String warehouse;
	public Integer ats;
}