public with sharing class BL_WECHAT_Constants {

    //USECASE
    public static final String USE_CASE_WECHAT_CLIENT                             = 'WeChat Client';
    public static final String USE_CASE_WECHAT_CLIENT_ADDRESS                     = 'WeChat Client Address';
    public static final String USE_CASE_WECHAT_SA_CLIENT                          = 'WeChat SA Client';
    public static final String USE_CASE_USER                                      = 'Me';
    
    //Custom Settings
    public static String defaultLastname = BL_WECHAT_CustomSettingsMgr.self().getDefaultLastname();
   // public static String defaultCreationStore = BL_WECHAT_CustomSettingsMgr.self().getDefaultCreationStore();
   // public static String defaultCreationSA = BL_WECHAT_CustomSettingsMgr.self().getDefaultCreationSA();
   

}