@isTest
private class CLT_Utils_Mapping_Test {
	
	@isTest static void test_method_one() {
		//Map<String, String> params = new Map<String, String>();
		//Map<String, Object> body = new Map<String, Object>();
		//params.put('', '');

		//Test.startTest();
		
		//CLT_Utils_Mapping.getMappingByObject('Account');
		//CLT_Utils_Mapping.getMappingObjectDict('SFFieldPath__c', 'Account');
		//CLT_Utils_Mapping.getQueryString('Event', 'SELECT Id From ');
		//CLT_Utils_Mapping.getStandardWrapperList('Event', 'SELECT Id From ');
		//CLT_Utils_Mapping.getStandardWrapperList('Account', null);
		//Test.stopTest();
	}
	
}