public with sharing class SOM_Wr_ShipmentTranslation {
    @AuraEnabled
    public String foliNumber;
    @AuraEnabled
    public String sku;
    @AuraEnabled
    public Integer quantity;
    @AuraEnabled
    public String serialNumber;
    @AuraEnabled
    public String tracking;
    @AuraEnabled
    public Datetime dispatchDate;
    @AuraEnabled
    public String deliveryMethod;
    @AuraEnabled
    public String sku10Digits;

}