/*     
-------------------------------------------------------------------------------------------
-- - Name               : TNP_001_AccountWrapper  
-- - Author             : Ulrich N. N.
-- - Description        : Wrapper for the TNP_001
--    
-- Date         Name  Version  Remarks 
-- -----------  ----  -------  ------------------------------------------------------------
-- 10/10/2023    UNN    1.0      Intitial version
-------------------------------------------------------------------------------------------
*/
public class TNP_001_AccountWrapper {
    public List<Account> cdpAccountList = new List<Account>();
    public List<Account> otherAccountList = new List<Account>();
}