name: Run Specified Test Classes

on:
  workflow_dispatch:
  push:
    paths:
      - force-app/**
      - specifiedTestsClass/testsToRun.txt

jobs:
  run-specified-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SFDX CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Install Apex Plugin (for force:apex:test:run)
        run: |
          sfdx plugins:install @salesforce/plugin-apex

      - name: Login to Salesforce Org
        run: |
          sfdx auth:sfdxurl:store --sfdxurlfile <(echo "${{ secrets.SFDC_AUTH_URL }}") --setdefaultusername

      - name: Read Test Class Names from File
        id: read-tests
        run: |
          TEST_CLASSES=$(tr '\n' ',' < specifiedTestsClass/testsToRun.txt | sed 's/,$//')
          echo "Running test classes: $TEST_CLASSES"
          echo "TEST_CLASSES=$TEST_CLASSES" >> $GITHUB_OUTPUT

      - name: Run Specified Test Classes
        run: |
          sfdx force:apex:test:run -n "${{ steps.read-tests.outputs.TEST_CLASSES }}" -w 15 --resultformat human --outputdir test-results

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apex-test-results
          path: test-results
