name: Deploy and Run Tests with JWT Auth

on:
  workflow_dispatch:
  push:
    paths:
      - force-app/**
      - specifiedTestsClass/testsToRun.txt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      - name: Authenticate using JWT
        run: |
          echo "${{ secrets.SFDC_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id "${{ secrets.SFDC_CLIENT_ID }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SFDC_USERNAME }}" \
            --instance-url "${{ secrets.SFDC_LOGIN_URL }}" \
            --set-default

      - name: Deploy Source
        run: |
          sf project deploy start --source-dir force-app --wait 10

      - name: Read Test Class Names from File
        id: test-classes
        run: |
          TEST_CLASSES=$(tr '\n' ',' < specifiedTestsClass/testsToRun.txt | sed 's/,$//')
          echo "Test classes to run: $TEST_CLASSES"
          echo "TEST_CLASSES=$TEST_CLASSES" >> $GITHUB_OUTPUT

      - name: Run Specified Apex Tests
        run: |
          sf apex run test \
            --tests "${{ steps.test-classes.outputs.TEST_CLASSES }}" \
            --wait 20 \
            --result-format human \
            --output-dir test-results

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apex-test-results
          path: test-results
